name: deployment
on:
  push:
    tags:
      - feature
jobs:
  deploy:
    runs-on:
      - self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: cargo install mzoon --git https://github.com/MoonZoon/MoonZoon --locked
      - run: mzoon start --release
