name: deployment
on: [push]
jobs:
  deploy:
    runs-on:
      - self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: cargo install mzoon --git https://github.com/MoonZoon/MoonZoon --branch main --locked
      - run: mzoon start --release
