name: deployment
on: [push]
jobs:
  deploy:
    runs-on:
      - self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install npm
      - run: sudo npm install -g cargo
      - run: cargo install mzoon --git https://github.com/MoonZoon/MoonZoon --branch main --locked
      - run: mzoon start --release
