name: deployment
on: [push]
jobs:
  deploy:
    runs-on:
      - self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: mzoon --git https://github.com/MoonZoon/MoonZoon --branch main --locked
      - run: mzoon start --release
