name: deployment
on: [push]
jobs:
  deploy:
    runs-on:
      - self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: apt install cargo
      - run: cargo install mzoon --git https://github.com/MoonZoon/MoonZoon --locked
      - run: mzoon start --release
      - run: uninstall mzoon
